package com.libertasprimordium.skald.security

enum class VaultCryptoDependencyCandidate(val label: String) {
    TinkBouncyCastleSplit("Tink AEAD plus Bouncy Castle Argon2id"),
    LazysodiumJavaAndroid("Lazysodium Java/Android libsodium binding"),
    IonSpinKmpLibsodium("IonSpin Kotlin Multiplatform libsodium binding"),
    BouncyCastleOnly("Bouncy Castle provider only"),
    PlatformCryptoOnly("platform crypto only"),
    KotlinMultiplatformCrypto("other Kotlin Multiplatform crypto candidate"),
}

enum class VaultCryptoDependencyProbeStatus(val label: String) {
    SelectedForPackagingProbe("selected for packaging probe"),
    DesktopKatValidatedCandidate("desktop KAT-validated candidate"),
    AndroidRuntimeKatValidatedCandidate("Android runtime KAT-validated candidate"),
    PackagingProbeOnly("packaging probe only"),
    DeferredAfterComparison("deferred after comparison"),
    DeferredPendingReview("deferred pending review"),
    RejectedForCurrentVault("rejected for current vault"),
    InsufficientAsPrimaryVaultStack("insufficient as primary vault stack"),
    RejectedAsDefaultVaultStack("rejected as default vault stack"),
}

enum class VaultCryptoDependencyCapability(val label: String) {
    Argon2idApiPresent("Argon2id API present"),
    ScryptApiPresent("scrypt API present"),
    XChaCha20Poly1305ApiPresent("XChaCha20-Poly1305 API present"),
    ChaCha20Poly1305ApiPresent("ChaCha20-Poly1305 API present"),
    AeadApiPresent("AEAD API present"),
    HkdfOrPrfApiPresent("HKDF or PRF API present"),
    DesktopKnownAnswerVectorsPass("desktop known-answer vectors pass"),
    DesktopRuntimeProbePass("desktop runtime probe passes"),
    AndroidKnownAnswerVectorTestsPresent("Android known-answer vector tests present"),
    AndroidKnownAnswerVectorsPass("Android known-answer vectors pass"),
    AndroidTestApkAssemblyPass("Android test APK assembly passes"),
    KnownAnswerVectorReviewRequired("additional known-answer vector review required"),
    AndroidArtifactPinned("Android artifact pinned"),
    DesktopArtifactPinned("Linux desktop artifact pinned"),
    AndroidNativeAbiLibrariesPresent("Android native ABI libraries present"),
    LinuxNativeLibrariesPresent("Linux native libraries present"),
    PureJvmNoNativeLibraries("pure JVM/Android artifacts; no native libraries"),
    NativeLibrariesRequired("native libraries required"),
    SinglePrimitiveFamily("KDF and AEAD come from one primitive family"),
    SecretStreamApiPresent("XChaCha20-Poly1305 secretstream API present"),
    FixedNonceKnownAnswerVectorFeasible("fixed-nonce public KAT appears feasible"),
    SplitProviderStack("KDF and AEAD come from separate providers"),
}

enum class VaultCryptoDependencyBlocker(val label: String) {
    DependencyReviewIncomplete("dependency review incomplete"),
    LicenseReviewIncomplete("license review incomplete"),
    KdfCalibrationMissing("KDF calibration missing"),
    KnownAnswerVectorTestsMissing("known-answer vector tests missing"),
    AndroidKnownAnswerVectorRuntimeMissing("Android known-answer vector runtime probe missing"),
    AndroidKnownAnswerVectorRuntimeUnverified("Android known-answer vector runtime execution unverified"),
    AndroidRuntimeInstallConflict("Android runtime test blocked by connected-device install conflict"),
    NativePackagingUnverified("native packaging unverified"),
    NativePackagingReviewRequired("native packaging review required"),
    NativeLoaderRuntimeRisk("native loader runtime risk remains"),
    AndroidDuplicateJnaClasspath("Android package fails with duplicate JNA classes"),
    KotlinMultiplatformCompatibilityUnverified("Kotlin Multiplatform compatibility unverified"),
    AndroidRuntimeProbeMissing("Android runtime probe missing"),
    DoesNotProvidePreferredAead("does not provide preferred XChaCha20-Poly1305 AEAD"),
    DoesNotProvideArgon2id("does not provide Argon2id"),
    RequiresSplitProviderDesign("requires split-provider design"),
    ProductionProviderBoundaryMissing("production crypto provider boundary missing"),
    TinkKeysetStorageHandlingReviewMissing("Tink keyset/storage handling review missing"),
    SplitProviderBoundaryReviewMissing("split-provider boundary review missing"),
    LockSessionLifecycleTestsMissing("lock/session lifecycle tests missing"),
    MigrationCorruptionTestsMissing("migration/corruption tests missing"),
    ProductionStorageReviewMissing("production storage review missing"),
    MainnetReleaseHardeningReviewMissing("mainnet release-hardening review missing"),
    VaultImplementationStillDisabled("vault implementation still disabled"),
}

data class VaultCryptoDependencyProbeResult(
    val candidate: VaultCryptoDependencyCandidate,
    val status: VaultCryptoDependencyProbeStatus,
    val pinnedArtifacts: List<String>,
    val capabilities: Set<VaultCryptoDependencyCapability>,
    val blockers: Set<VaultCryptoDependencyBlocker>,
    val implementationEnabled: Boolean,
    val storageEnabled: Boolean,
    val productionPersistenceEnabled: Boolean,
    val mainnetEnabled: Boolean,
    val note: String,
) {
    val readyForVaultImplementation: Boolean
        get() = implementationEnabled &&
            storageEnabled &&
            productionPersistenceEnabled &&
            blockers.isEmpty()
}

object VaultCryptoDependencyProbeCatalog {
    fun currentSpikeResults(): List<VaultCryptoDependencyProbeResult> =
        listOf(
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.TinkBouncyCastleSplit,
                status = VaultCryptoDependencyProbeStatus.AndroidRuntimeKatValidatedCandidate,
                pinnedArtifacts = listOf(
                    "com.google.crypto.tink:tink-android:1.21.0",
                    "com.google.crypto.tink:tink:1.21.0",
                    "org.bouncycastle:bcprov-jdk18on:1.84",
                ),
                capabilities = setOf(
                    VaultCryptoDependencyCapability.Argon2idApiPresent,
                    VaultCryptoDependencyCapability.XChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.ChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.AeadApiPresent,
                    VaultCryptoDependencyCapability.HkdfOrPrfApiPresent,
                    VaultCryptoDependencyCapability.DesktopKnownAnswerVectorsPass,
                    VaultCryptoDependencyCapability.DesktopRuntimeProbePass,
                    VaultCryptoDependencyCapability.AndroidKnownAnswerVectorTestsPresent,
                    VaultCryptoDependencyCapability.AndroidKnownAnswerVectorsPass,
                    VaultCryptoDependencyCapability.AndroidTestApkAssemblyPass,
                    VaultCryptoDependencyCapability.KnownAnswerVectorReviewRequired,
                    VaultCryptoDependencyCapability.AndroidArtifactPinned,
                    VaultCryptoDependencyCapability.DesktopArtifactPinned,
                    VaultCryptoDependencyCapability.PureJvmNoNativeLibraries,
                    VaultCryptoDependencyCapability.SplitProviderStack,
                ),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DependencyReviewIncomplete,
                    VaultCryptoDependencyBlocker.LicenseReviewIncomplete,
                    VaultCryptoDependencyBlocker.KdfCalibrationMissing,
                    VaultCryptoDependencyBlocker.RequiresSplitProviderDesign,
                    VaultCryptoDependencyBlocker.ProductionProviderBoundaryMissing,
                    VaultCryptoDependencyBlocker.TinkKeysetStorageHandlingReviewMissing,
                    VaultCryptoDependencyBlocker.SplitProviderBoundaryReviewMissing,
                    VaultCryptoDependencyBlocker.LockSessionLifecycleTestsMissing,
                    VaultCryptoDependencyBlocker.MigrationCorruptionTestsMissing,
                    VaultCryptoDependencyBlocker.ProductionStorageReviewMissing,
                    VaultCryptoDependencyBlocker.MainnetReleaseHardeningReviewMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Selected only for Android/Linux compile and packaging feasibility plus desktop and Android runtime public KAT validation. Android runtime KATs passed on Pixel 10 Pro XL / Android 16 after targeting the raw ADB IP:port serial; earlier connected-device failures were environment/install-targeting blockers, not KAT failures. It is not wired into vault storage.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.LazysodiumJavaAndroid,
                status = VaultCryptoDependencyProbeStatus.RejectedForCurrentVault,
                pinnedArtifacts = listOf(
                    "com.goterl:lazysodium-java:5.2.0",
                    "com.goterl:lazysodium-android:5.2.0",
                ),
                capabilities = setOf(
                    VaultCryptoDependencyCapability.Argon2idApiPresent,
                    VaultCryptoDependencyCapability.ScryptApiPresent,
                    VaultCryptoDependencyCapability.XChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.AeadApiPresent,
                    VaultCryptoDependencyCapability.HkdfOrPrfApiPresent,
                    VaultCryptoDependencyCapability.AndroidArtifactPinned,
                    VaultCryptoDependencyCapability.DesktopArtifactPinned,
                    VaultCryptoDependencyCapability.AndroidNativeAbiLibrariesPresent,
                    VaultCryptoDependencyCapability.LinuxNativeLibrariesPresent,
                    VaultCryptoDependencyCapability.NativeLibrariesRequired,
                    VaultCryptoDependencyCapability.SinglePrimitiveFamily,
                    VaultCryptoDependencyCapability.SecretStreamApiPresent,
                    VaultCryptoDependencyCapability.FixedNonceKnownAnswerVectorFeasible,
                ),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DependencyReviewIncomplete,
                    VaultCryptoDependencyBlocker.LicenseReviewIncomplete,
                    VaultCryptoDependencyBlocker.KdfCalibrationMissing,
                    VaultCryptoDependencyBlocker.AndroidDuplicateJnaClasspath,
                    VaultCryptoDependencyBlocker.NativePackagingUnverified,
                    VaultCryptoDependencyBlocker.NativePackagingReviewRequired,
                    VaultCryptoDependencyBlocker.NativeLoaderRuntimeRisk,
                    VaultCryptoDependencyBlocker.KnownAnswerVectorTestsMissing,
                    VaultCryptoDependencyBlocker.AndroidKnownAnswerVectorRuntimeMissing,
                    VaultCryptoDependencyBlocker.AndroidRuntimeProbeMissing,
                    VaultCryptoDependencyBlocker.ProductionProviderBoundaryMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Rejected for the current vault branch because the Android package probe failed with duplicate JNA classes before APK output. It is not wired into vault storage or approved for production implementation.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.IonSpinKmpLibsodium,
                status = VaultCryptoDependencyProbeStatus.DeferredAfterComparison,
                pinnedArtifacts = listOf(
                    "com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.9.5",
                    "com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings-jvm:0.9.5",
                    "com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings-android:0.9.5",
                ),
                capabilities = setOf(
                    VaultCryptoDependencyCapability.Argon2idApiPresent,
                    VaultCryptoDependencyCapability.ScryptApiPresent,
                    VaultCryptoDependencyCapability.XChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.NativeLibrariesRequired,
                    VaultCryptoDependencyCapability.SinglePrimitiveFamily,
                ),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DependencyReviewIncomplete,
                    VaultCryptoDependencyBlocker.LicenseReviewIncomplete,
                    VaultCryptoDependencyBlocker.NativePackagingUnverified,
                    VaultCryptoDependencyBlocker.KotlinMultiplatformCompatibilityUnverified,
                    VaultCryptoDependencyBlocker.KnownAnswerVectorTestsMissing,
                    VaultCryptoDependencyBlocker.AndroidKnownAnswerVectorRuntimeMissing,
                    VaultCryptoDependencyBlocker.AndroidRuntimeProbeMissing,
                    VaultCryptoDependencyBlocker.ProductionProviderBoundaryMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Inspected as an exact KMP libsodium candidate but deferred from the build because the current spike did not validate its Kotlin metadata, native-loader behavior, or package outputs.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.BouncyCastleOnly,
                status = VaultCryptoDependencyProbeStatus.InsufficientAsPrimaryVaultStack,
                pinnedArtifacts = listOf("org.bouncycastle:bcprov-jdk18on:1.84"),
                capabilities = setOf(
                    VaultCryptoDependencyCapability.Argon2idApiPresent,
                    VaultCryptoDependencyCapability.ChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.AeadApiPresent,
                    VaultCryptoDependencyCapability.PureJvmNoNativeLibraries,
                ),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DoesNotProvidePreferredAead,
                    VaultCryptoDependencyBlocker.KdfCalibrationMissing,
                    VaultCryptoDependencyBlocker.KnownAnswerVectorTestsMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Useful Argon2id provider candidate, but not enough alone for the preferred XChaCha record envelope.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.PlatformCryptoOnly,
                status = VaultCryptoDependencyProbeStatus.RejectedAsDefaultVaultStack,
                pinnedArtifacts = emptyList(),
                capabilities = setOf(VaultCryptoDependencyCapability.AeadApiPresent),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DoesNotProvideArgon2id,
                    VaultCryptoDependencyBlocker.DoesNotProvidePreferredAead,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Rejected as the default vault stack because it pushes toward PBKDF2/AES-GCM-only storage.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.KotlinMultiplatformCrypto,
                status = VaultCryptoDependencyProbeStatus.DeferredPendingReview,
                pinnedArtifacts = emptyList(),
                capabilities = emptySet(),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DependencyReviewIncomplete,
                    VaultCryptoDependencyBlocker.NativePackagingUnverified,
                    VaultCryptoDependencyBlocker.KnownAnswerVectorTestsMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Deferred unless a clearly maintained KMP stack proves Android/Linux packaging and the preferred primitive set.",
            ),
        )
}
