package com.libertasprimordium.skald.security

enum class VaultCryptoDependencyCandidate(val label: String) {
    TinkBouncyCastleSplit("Tink AEAD plus Bouncy Castle Argon2id"),
    LazysodiumJavaAndroid("Lazysodium Java/Android libsodium binding"),
    IonSpinKmpLibsodium("IonSpin Kotlin Multiplatform libsodium binding"),
    BouncyCastleOnly("Bouncy Castle provider only"),
    PlatformCryptoOnly("platform crypto only"),
    KotlinMultiplatformCrypto("other Kotlin Multiplatform crypto candidate"),
}

enum class VaultCryptoDependencyProbeStatus(val label: String) {
    SelectedForPackagingProbe("selected for packaging probe"),
    DesktopKatValidatedCandidate("desktop KAT-validated candidate"),
    AndroidRuntimeKatValidatedCandidate("Android runtime KAT-validated candidate"),
    DependencyLicenseAndKeysetReviewCompleteCandidate("dependency, license, and keyset review complete candidate"),
    PackagingProbeOnly("packaging probe only"),
    DeferredAfterComparison("deferred after comparison"),
    DeferredPendingReview("deferred pending review"),
    RejectedForCurrentVault("rejected for current vault"),
    InsufficientAsPrimaryVaultStack("insufficient as primary vault stack"),
    RejectedAsDefaultVaultStack("rejected as default vault stack"),
}

enum class VaultCryptoDependencyCapability(val label: String) {
    Argon2idApiPresent("Argon2id API present"),
    ScryptApiPresent("scrypt API present"),
    XChaCha20Poly1305ApiPresent("XChaCha20-Poly1305 API present"),
    ChaCha20Poly1305ApiPresent("ChaCha20-Poly1305 API present"),
    AeadApiPresent("AEAD API present"),
    HkdfOrPrfApiPresent("HKDF or PRF API present"),
    DesktopKnownAnswerVectorsPass("desktop known-answer vectors pass"),
    DesktopRuntimeProbePass("desktop runtime probe passes"),
    AndroidKnownAnswerVectorTestsPresent("Android known-answer vector tests present"),
    AndroidKnownAnswerVectorsPass("Android known-answer vectors pass"),
    AndroidTestApkAssemblyPass("Android test APK assembly passes"),
    KnownAnswerVectorReviewRequired("additional known-answer vector review required"),
    DependencyInventoryReviewed("dependency inventory reviewed"),
    LicenseDeclarationsInspected("license declarations inspected"),
    PackageInventoriesReviewed("APK and deb package inventories reviewed"),
    TinkKeysetStorageReviewDocumented("Tink keyset/storage handling review documented"),
    TinkRawKeyFeasibilityPublicApiProbePass("Tink raw-key public API feasibility probe passes"),
    AndroidTinkRawKeyFeasibilityPublicApiProbePass("Android Tink raw-key public API feasibility probe passes"),
    AndroidTinkRawKeyFeasibilityPublicApiProbePresent(
        "Android Tink raw-key public API feasibility probe present",
    ),
    CrossPlatformTinkRawKeyFeasibilityPublicApiProbePass(
        "desktop and Android Tink raw-key public API feasibility probes pass",
    ),
    BouncyCastleArgon2idApiRisksDocumented("Bouncy Castle Argon2id API risks documented"),
    SplitProviderBoundaryReviewDocumented("split-provider boundary review documented"),
    FutureProviderBoundaryPrerequisitesDocumented("future provider-boundary prerequisites documented"),
    DisabledProviderBoundaryModeled("disabled Skald-owned provider boundary modeled"),
    ProviderSelectionBoundaryModeled("provider selection boundary modeled"),
    ProviderKatContractModeled("provider-level KAT contract modeled"),
    ProviderLevelKatStrategyContractModeled("provider-level KAT strategy contract modeled"),
    RandomizedAeadBehavioralKatPolicyModeled("randomized AEAD behavioral KAT policy modeled"),
    IntegratedVerificationOrderKatPolicyModeled("integrated verification-order KAT policy modeled"),
    StaleRecordManifestPolicyModeled("stale-record and rollback manifest policy modeled"),
    TestOnlyProviderKatHarnessPresent("test-only provider-level KAT harness present"),
    StillDisabledProviderIntegrationHarnessTested("still-disabled provider integration harness tested"),
    ProviderLevelKatsExecutedInStillDisabledHarness(
        "provider-level KATs execute in still-disabled harness",
    ),
    RandomizedAeadBehavioralKatsExecutedInStillDisabledHarness(
        "randomized AEAD behavioral KATs execute in still-disabled harness",
    ),
    IntegratedVerificationOrderKatsExecutedInStillDisabledHarness(
        "integrated verification-order KATs execute in still-disabled harness",
    ),
    StillDisabledProviderFacadeBoundaryModeled(
        "still-disabled provider facade boundary modeled",
    ),
    VaultContainerContractModeled("vault container contract modeled"),
    InMemoryVaultContainerParserWriterTested(
        "in-memory vault container parser/writer building block tested",
    ),
    ManifestContractModeled("manifest contract modeled"),
    InMemoryManifestParserWriterTested(
        "in-memory manifest parser/writer building block tested",
    ),
    LocalManifestStaleRecordDecisionPolicyTested(
        "local manifest-relative stale-record decision policy tested",
    ),
    StoragePolicyContractModeled("storage policy contract modeled"),
    PlatformStorageBoundaryContractModeled("platform storage boundary contract modeled"),
    AtomicityCrashRecoveryContractModeled("atomicity and crash-recovery contract modeled"),
    AtomicWriteStrategyContractModeled("atomic write strategy contract modeled"),
    CrashRecoveryContractModeled("crash-recovery contract modeled"),
    StorageInterruptionTestContractModeled("storage interruption-test contract modeled"),
    InMemoryStorageAtomicityCrashSimulatorTested(
        "in-memory storage atomicity/crash simulator tested",
    ),
    StorageFailureModelContractModeled("storage failure model contract modeled"),
    StorageNamespacePathHygieneContractModeled("storage namespace/path hygiene contract modeled"),
    StorageNamespacePathPolicyImplementedTested(
        "storage namespace/path policy implemented and tested",
    ),
    StorageLayoutPlanImplementedTested(
        "rootless logical storage layout plan implemented and tested",
    ),
    PathContainmentPlannerImplementedTested(
        "path-containment planner implemented and tested",
    ),
    PlatformStorageRootContractModeled("platform storage root contract modeled"),
    PlatformRootSettingsPolicyModeled("platform root settings policy modeled"),
    AndroidAppPrivateRootPolicyModeled("Android app-private internal root policy modeled"),
    LinuxRootSettingsPolicyModeled("Linux root settings policy modeled"),
    LinuxCustomRootValidationPolicyImplementedTested(
        "Linux custom root validation policy implemented and tested",
    ),
    LinuxRootResolutionPolicyImplementedTested(
        "Linux root-resolution evidence policy implemented and tested",
    ),
    PlatformRootResolverBoundaryImplementedTested(
        "platform root resolver boundary implemented and tested",
    ),
    PlatformPathConstructionBoundaryImplementedTested(
        "platform path-construction boundary implemented and tested",
    ),
    StorageSafetyPreflightBoundaryImplementedTested(
        "storage safety preflight boundary implemented and tested",
    ),
    DisabledStorageServiceFacadeImplementedTested(
        "disabled vault storage service facade implemented and tested",
    ),
    StorageOperationFailureVocabularyModeled("disabled storage operation failure vocabulary modeled"),
    PersistenceReadinessGateImplementedTested("vault persistence readiness gate implemented and tested"),
    PersistenceReadinessFailureVocabularyModeled("vault persistence readiness failure vocabulary modeled"),
    LockSessionLifecycleBoundaryImplementedTested("vault lock/session lifecycle boundary implemented and tested"),
    LockSessionFailureVocabularyModeled("vault lock/session lifecycle failure vocabulary modeled"),
    RedactionLeakageBoundaryImplementedTested("vault redaction/leakage boundary implemented and tested"),
    RedactionLeakageFailureVocabularyModeled("vault redaction/leakage failure vocabulary modeled"),
    PassphrasePolicyBoundaryImplementedTested("vault passphrase policy boundary implemented and tested"),
    PassphrasePolicyFailureVocabularyModeled("vault passphrase policy failure vocabulary modeled"),
    ClearWipeStrategyBoundaryImplementedTested("vault clear/wipe strategy boundary implemented and tested"),
    ClearWipeFailureVocabularyModeled("vault clear/wipe failure vocabulary modeled"),
    MigrationCorruptionBoundaryImplementedTested(
        "vault migration/corruption boundary implemented and tested",
    ),
    MigrationCorruptionFailureVocabularyModeled("vault migration/corruption failure vocabulary modeled"),
    ProviderOperationAuthorizationBoundaryImplementedTested(
        "vault provider operation authorization boundary implemented and tested",
    ),
    ProviderOperationFailureVocabularyModeled("vault provider operation failure vocabulary modeled"),
    RuntimeRandomnessAuthorizationBoundaryImplementedTested(
        "vault runtime randomness authorization boundary implemented and tested",
    ),
    RuntimeRandomnessFailureVocabularyModeled("vault runtime randomness authorization failure vocabulary modeled"),
    KdfCalibrationAuthorizationBoundaryImplementedTested(
        "vault KDF calibration authorization boundary implemented and tested",
    ),
    KdfCalibrationAuthorizationFailureVocabularyModeled(
        "vault KDF calibration authorization failure vocabulary modeled",
    ),
    OsKeyringPassphraseStorageRejected("OS keyring passphrase storage rejected"),
    PasswordManagerIntegrationRejected("password-manager integration rejected"),
    PassphraseFirstVaultAuthorityModeled("passphrase-first vault authority modeled"),
    SafePathConstructionContractModeled("safe path-construction contract modeled"),
    SymlinkTraversalContractModeled("symlink and filesystem traversal contract modeled"),
    StoragePermissionOwnershipContractModeled("storage permission and ownership contract modeled"),
    DurabilityCapabilityContractModeled("durability capability contract modeled"),
    DurabilityFailClosedPolicyModeled("durability fail-closed policy modeled"),
    WarningOnlyDurabilityRejectionModeled("warning-only durability rejection modeled"),
    RollbackLimitationAntiRollbackAnchorModeled(
        "rollback limitation and anti-rollback anchor status modeled",
    ),
    SecureStorageBoundaryContractModeled("secure storage boundary contract modeled"),
    Argon2idCalibrationPolicyModeled("Argon2id calibration policy modeled"),
    Argon2idCandidateParameterPolicyModeled("Argon2id candidate parameter policy modeled"),
    Argon2idCalibrationPolicyImplementedTested(
        "Argon2id calibration policy building block implemented and tested",
    ),
    Argon2idCandidateSelectionPolicyImplementedTested(
        "Argon2id calibration candidate-selection policy implemented and tested",
    ),
    Argon2idMemoryFailureHandlingModeledTested(
        "Argon2id calibration memory/execution failure handling modeled and tested",
    ),
    Argon2idStoredParameterNoDowngradeModeledTested(
        "Argon2id stored-parameter no-downgrade behavior modeled and tested",
    ),
    AndroidArgon2idCalibrationEvidenceCaptureModeled("Android Argon2id calibration evidence capture modeled"),
    AndroidCompatibilityEntropyPolicyModeled("Android compatibility and entropy policy modeled"),
    RuntimeRandomnessProviderChecksModeled("runtime randomness provider checks modeled"),
    ProductionProviderAcceptanceContractModeled("production provider acceptance contract modeled"),
    VaultHeaderCommitmentPolicyModeled("vault header commitment policy modeled"),
    HkdfSha256KeyExpansionPolicyModeled("HKDF-SHA-256 key-expansion policy modeled"),
    HmacSha256HeaderCommitmentPrimitiveModeled("HMAC-SHA-256 header-commitment primitive modeled"),
    KeyExpansionOutputLayoutModeled("key-expansion output layout modeled"),
    PrimitiveThreatModelRationaleModeled("primitive threat model and rationale modeled"),
    CanonicalHeaderByteVectorContractModeled("canonical header byte vector contract modeled"),
    HkdfSha256VectorContractModeled("HKDF-SHA-256 vector contract modeled"),
    HmacSha256HeaderCommitmentVectorContractModeled(
        "HMAC-SHA-256 header-commitment vector contract modeled",
    ),
    CanonicalHeaderEncodingPolicyModeled("canonical header encoding policy modeled"),
    KeySeparationLabelsPolicyModeled("key-separation labels policy modeled"),
    CanonicalHeaderSerializerVectorTested(
        "canonical header serializer implementation matches the non-secret vector",
    ),
    HkdfSha256KeyExpansionVectorTested(
        "HKDF-SHA-256 key-expansion implementation matches the non-secret vectors",
    ),
    HmacSha256HeaderCommitmentVectorTested(
        "HMAC-SHA-256 header-commitment implementation matches the non-secret vector",
    ),
    StrictAadContractPolicyModeled("strict AEAD associated-data contract policy modeled"),
    StrictAadSerializationVectorTested(
        "strict AEAD associated-data serialization matches the non-secret vector",
    ),
    TinkRecordAeadBuildingBlockTested(
        "Tink XChaCha20-Poly1305 record AEAD building block matches non-secret behavior tests",
    ),
    TinkNonKeyCommitmentMitigationModeled("Tink non-key-commitment mitigation modeled"),
    PassphraseEncodingPolicyModeled("passphrase encoding policy modeled"),
    PassphrasePolicyValidationImplemented(
        "passphrase policy validation implementation matches fixed non-secret tests",
    ),
    Argon2idPassphraseRootDerivationVectorTested(
        "Bouncy Castle Argon2id explicit-parameter root derivation matches the non-secret fixture",
    ),
    TinkRawKeyFeasibilityPolicyModeled("Tink raw-key feasibility policy modeled"),
    Argon2idBoundedCalibrationPolicyModeled("bounded Argon2id calibration policy modeled"),
    Argon2idCalibrationProbeOnly("Argon2id calibration probe-only status modeled"),
    AndroidArtifactPinned("Android artifact pinned"),
    DesktopArtifactPinned("Linux desktop artifact pinned"),
    AndroidNativeAbiLibrariesPresent("Android native ABI libraries present"),
    LinuxNativeLibrariesPresent("Linux native libraries present"),
    PureJvmNoNativeLibraries("pure JVM/Android artifacts; no native libraries"),
    NativeLibrariesRequired("native libraries required"),
    SinglePrimitiveFamily("KDF and AEAD come from one primitive family"),
    SecretStreamApiPresent("XChaCha20-Poly1305 secretstream API present"),
    FixedNonceKnownAnswerVectorFeasible("fixed-nonce public KAT appears feasible"),
    SplitProviderStack("KDF and AEAD come from separate providers"),
}

enum class VaultCryptoDependencyBlocker(val label: String) {
    DependencyReviewIncomplete("dependency review incomplete"),
    LicenseReviewIncomplete("license review incomplete"),
    KdfCalibrationMissing("KDF calibration missing"),
    KdfFinalParameterApprovalMissing("final KDF parameter approval missing"),
    KnownAnswerVectorTestsMissing("known-answer vector tests missing"),
    AndroidKnownAnswerVectorRuntimeMissing("Android known-answer vector runtime probe missing"),
    AndroidKnownAnswerVectorRuntimeUnverified("Android known-answer vector runtime execution unverified"),
    AndroidRuntimeInstallConflict("Android runtime test blocked by connected-device install conflict"),
    NativePackagingUnverified("native packaging unverified"),
    NativePackagingReviewRequired("native packaging review required"),
    NativeLoaderRuntimeRisk("native loader runtime risk remains"),
    AndroidDuplicateJnaClasspath("Android package fails with duplicate JNA classes"),
    KotlinMultiplatformCompatibilityUnverified("Kotlin Multiplatform compatibility unverified"),
    AndroidRuntimeProbeMissing("Android runtime probe missing"),
    DoesNotProvidePreferredAead("does not provide preferred XChaCha20-Poly1305 AEAD"),
    DoesNotProvideArgon2id("does not provide Argon2id"),
    RequiresSplitProviderDesign("requires split-provider design"),
    ProductionProviderBoundaryMissing("production crypto provider boundary missing"),
    ProductionProviderImplementationMissing("production crypto provider implementation missing"),
    ProviderSelectionProductionBlocked("provider selection production blocked"),
    ProductionProviderAcceptanceContractIncomplete("production provider acceptance contract incomplete"),
    ProviderLevelKatExecutionMissing("provider-level KAT execution missing"),
    ProviderLevelKatStrategyContractOnly("provider-level KAT strategy is contract/model evidence only"),
    RandomizedAeadBehavioralKatExecutionMissing("randomized AEAD behavioral KAT execution missing"),
    IntegratedVerificationOrderKatExecutionMissing("integrated verification-order KAT execution missing"),
    TinkKeysetStorageHandlingReviewMissing("Tink keyset/storage handling review missing"),
    TinkRawKeyFeasibilityApprovalMissing("Tink raw-key feasibility approval missing"),
    VaultHeaderCommitmentImplementationMissing("vault header commitment implementation missing"),
    HkdfSha256KeyExpansionImplementationMissing("HKDF-SHA-256 key expansion implementation missing"),
    HmacSha256HeaderCommitmentImplementationMissing("HMAC-SHA-256 header commitment implementation missing"),
    KeyExpansionOutputLayoutImplementationMissing("key-expansion output layout implementation missing"),
    CanonicalHeaderByteVectorProductionImplementationMissing(
        "canonical header byte vectors are test-scope only; production encoder missing",
    ),
    HkdfSha256VectorProductionImplementationMissing(
        "HKDF-SHA-256 vectors are test-scope only; production HKDF missing",
    ),
    HmacSha256HeaderCommitmentVectorProductionImplementationMissing(
        "HMAC-SHA-256 vectors are test-scope only; production header commitment missing",
    ),
    CanonicalHeaderEncodingImplementationMissing("canonical header encoding implementation missing"),
    KeySeparationImplementationMissing("key-separation implementation missing"),
    VaultHeaderCommitmentProviderIntegrationMissing(
        "vault header commitment building block is not wired into a provider",
    ),
    HkdfSha256KeyExpansionProviderIntegrationMissing(
        "HKDF-SHA-256 key expansion building block is not wired into a provider",
    ),
    HmacSha256HeaderCommitmentProviderIntegrationMissing(
        "HMAC-SHA-256 header commitment building block is not wired into a provider",
    ),
    KeyExpansionOutputLayoutProviderIntegrationMissing(
        "key-expansion output layout is not wired into a provider",
    ),
    CanonicalHeaderSerializerProviderIntegrationMissing(
        "canonical header serializer is not wired into a provider or vault format boundary",
    ),
    KeySeparationProviderIntegrationMissing(
        "key-separation output is not wired into a provider",
    ),
    StrictAadProviderIntegrationMissing(
        "strict AEAD associated-data building block is not wired into a provider",
    ),
    TinkRecordAeadProviderIntegrationMissing(
        "Tink record AEAD building block is not wired into a provider",
    ),
    StillDisabledProviderIntegrationHarnessNotSelectable(
        "still-disabled provider integration harness is not a selectable production provider",
    ),
    StillDisabledProviderFacadeNotSelectable(
        "still-disabled provider facade is not a selectable production provider",
    ),
    StaleRecordManifestIntegrationMissing(
        "record version/counter binding is not backed by a trusted manifest or storage index",
    ),
    StaleRecordManifestPolicyImplementationMissing(
        "stale-record and rollback manifest policy is not implemented",
    ),
    VaultContainerStorageContractOnly("vault container/storage contract is documented and modeled only"),
    VaultContainerPersistenceImplementationMissing(
        "vault container parser/writer is in-memory only; persistence implementation missing",
    ),
    ManifestReadWriteImplementationMissing("manifest storage read/write implementation missing"),
    StorageSuccessPathAbsent("storage success path absent"),
    DisabledStorageServiceFacadeStillDisabled("disabled storage service facade has no storage success path"),
    PersistenceReadinessGateStillBlocked("vault persistence readiness gate still blocked"),
    PlatformStorageImplementationMissing("platform storage implementation missing"),
    AtomicWriteImplementationMissing("atomic write implementation missing"),
    CrashRecoveryImplementationMissing("crash-recovery implementation missing"),
    StorageInterruptionTestsMissing("storage interruption tests missing"),
    StorageFailureRuntimeMappingMissing("storage failure runtime mapping missing"),
    StorageNamespacePathImplementationMissing("storage namespace/path implementation missing"),
    StoragePathConstructionImplementationMissing("actual storage path construction implementation missing"),
    PlatformStorageRootImplementationMissing("platform storage root resolution implementation missing"),
    PlatformRootSettingsImplementationMissing("platform root settings implementation missing"),
    SettingsUiImplementationMissing("vault storage-root Settings UI implementation missing"),
    SettingsPersistenceImplementationMissing("vault storage-root settings persistence implementation missing"),
    LinuxCustomRootValidationMissing("Linux custom root validation missing"),
    SafePathConstructionImplementationMissing("safe storage path construction implementation missing"),
    SymlinkTraversalImplementationMissing("symlink and traversal check implementation missing"),
    StoragePermissionOwnershipImplementationMissing("storage permission and ownership check implementation missing"),
    DurabilityCapabilityProbeImplementationMissing("durability capability probe implementation missing"),
    DurabilityFailClosedRuntimeEvidenceMissing("durability fail-closed runtime evidence missing"),
    WarningOnlyDurabilityPersistenceRejected("warning-only durability persistence rejected"),
    AntiRollbackAnchorAbsentNoFullRollbackClaim(
        "anti-rollback anchor absent; full local-directory rollback resistance is not claimed",
    ),
    ManifestStorageAtomicityReviewMissing(
        "manifest/storage atomicity and crash-recovery review missing",
    ),
    PassphraseEncodingProductionValidationMissing("passphrase encoding production validation missing"),
    PassphrasePolicyProviderIntegrationMissing(
        "passphrase policy validation building block is not wired into a provider",
    ),
    Argon2idRootDerivationProviderIntegrationMissing(
        "Argon2id root derivation building block is not wired into a provider",
    ),
    Argon2idBoundedCalibrationApprovalMissing("bounded Argon2id calibration approval missing"),
    SplitProviderBoundaryReviewMissing("split-provider boundary review missing"),
    LockSessionLifecycleStillDisabled("vault lock/session lifecycle boundary still blocks unlock"),
    LockSessionLifecycleTestsMissing("lock/session lifecycle tests missing"),
    RedactionLeakageBoundaryStillDisabled("vault redaction/leakage boundary remains model-only"),
    RedactionLeakageRuntimeReviewMissing("runtime redaction/leakage review missing"),
    PassphrasePolicyBoundaryStillDisabled("vault passphrase policy boundary still blocks unlock"),
    PassphrasePolicyRuntimeReviewMissing("runtime passphrase policy review missing"),
    ClearWipeStrategyBoundaryStillDisabled("vault clear/wipe strategy boundary remains model-only"),
    ClearWipeStrategyRuntimeReviewMissing("runtime clear/wipe strategy review missing"),
    MigrationCorruptionBoundaryStillDisabled("vault migration/corruption boundary remains model-only"),
    MigrationCorruptionRuntimeReviewMissing("runtime migration/corruption handling review missing"),
    MigrationCorruptionTestsMissing("migration/corruption tests missing"),
    ProviderOperationAuthorizationBoundaryStillDisabled(
        "vault provider operation authorization boundary remains model-only",
    ),
    ProviderOperationAuthorizationRuntimeReviewMissing(
        "runtime provider operation authorization review missing",
    ),
    ProviderOperationAuthorizationTestsMissing("provider operation authorization tests missing"),
    RuntimeRandomnessAuthorizationBoundaryStillDisabled(
        "vault runtime randomness authorization boundary remains model-only",
    ),
    RuntimeRandomnessAuthorizationRuntimeReviewMissing(
        "runtime randomness authorization review missing",
    ),
    RuntimeRandomnessAuthorizationTestsMissing("runtime randomness authorization tests missing"),
    KdfCalibrationAuthorizationBoundaryStillDisabled(
        "vault KDF calibration authorization boundary remains model-only",
    ),
    KdfCalibrationAuthorizationRuntimeReviewMissing(
        "runtime KDF calibration authorization review missing",
    ),
    KdfCalibrationAuthorizationTestsMissing("KDF calibration authorization tests missing"),
    ProductionStorageReviewMissing("production storage review missing"),
    MainnetReleaseHardeningReviewMissing("mainnet release-hardening review missing"),
    VaultImplementationStillDisabled("vault implementation still disabled"),
}

data class VaultCryptoDependencyProbeResult(
    val candidate: VaultCryptoDependencyCandidate,
    val status: VaultCryptoDependencyProbeStatus,
    val pinnedArtifacts: List<String>,
    val capabilities: Set<VaultCryptoDependencyCapability>,
    val blockers: Set<VaultCryptoDependencyBlocker>,
    val implementationEnabled: Boolean,
    val storageEnabled: Boolean,
    val productionPersistenceEnabled: Boolean,
    val mainnetEnabled: Boolean,
    val note: String,
) {
    val readyForVaultImplementation: Boolean
        get() = implementationEnabled &&
            storageEnabled &&
            productionPersistenceEnabled &&
            blockers.isEmpty()
}

object VaultCryptoDependencyProbeCatalog {
    fun currentSpikeResults(): List<VaultCryptoDependencyProbeResult> =
        listOf(
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.TinkBouncyCastleSplit,
                status = VaultCryptoDependencyProbeStatus.DependencyLicenseAndKeysetReviewCompleteCandidate,
                pinnedArtifacts = listOf(
                    "com.google.crypto.tink:tink-android:1.21.0",
                    "com.google.crypto.tink:tink:1.21.0",
                    "org.bouncycastle:bcprov-jdk18on:1.84",
                ),
                capabilities = setOf(
                    VaultCryptoDependencyCapability.Argon2idApiPresent,
                    VaultCryptoDependencyCapability.XChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.ChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.AeadApiPresent,
                    VaultCryptoDependencyCapability.HkdfOrPrfApiPresent,
                    VaultCryptoDependencyCapability.DesktopKnownAnswerVectorsPass,
                    VaultCryptoDependencyCapability.DesktopRuntimeProbePass,
                    VaultCryptoDependencyCapability.AndroidKnownAnswerVectorTestsPresent,
                    VaultCryptoDependencyCapability.AndroidKnownAnswerVectorsPass,
                    VaultCryptoDependencyCapability.AndroidTestApkAssemblyPass,
                    VaultCryptoDependencyCapability.KnownAnswerVectorReviewRequired,
                    VaultCryptoDependencyCapability.DependencyInventoryReviewed,
                    VaultCryptoDependencyCapability.LicenseDeclarationsInspected,
                    VaultCryptoDependencyCapability.PackageInventoriesReviewed,
                    VaultCryptoDependencyCapability.TinkKeysetStorageReviewDocumented,
                    VaultCryptoDependencyCapability.TinkRawKeyFeasibilityPublicApiProbePass,
                    VaultCryptoDependencyCapability.AndroidTinkRawKeyFeasibilityPublicApiProbePresent,
                    VaultCryptoDependencyCapability.AndroidTinkRawKeyFeasibilityPublicApiProbePass,
                    VaultCryptoDependencyCapability.CrossPlatformTinkRawKeyFeasibilityPublicApiProbePass,
                    VaultCryptoDependencyCapability.BouncyCastleArgon2idApiRisksDocumented,
                    VaultCryptoDependencyCapability.SplitProviderBoundaryReviewDocumented,
                    VaultCryptoDependencyCapability.FutureProviderBoundaryPrerequisitesDocumented,
                    VaultCryptoDependencyCapability.DisabledProviderBoundaryModeled,
                    VaultCryptoDependencyCapability.ProviderSelectionBoundaryModeled,
                    VaultCryptoDependencyCapability.ProviderKatContractModeled,
                    VaultCryptoDependencyCapability.ProviderLevelKatStrategyContractModeled,
                    VaultCryptoDependencyCapability.RandomizedAeadBehavioralKatPolicyModeled,
                    VaultCryptoDependencyCapability.IntegratedVerificationOrderKatPolicyModeled,
                    VaultCryptoDependencyCapability.StaleRecordManifestPolicyModeled,
                    VaultCryptoDependencyCapability.TestOnlyProviderKatHarnessPresent,
                    VaultCryptoDependencyCapability.StillDisabledProviderIntegrationHarnessTested,
                    VaultCryptoDependencyCapability.ProviderLevelKatsExecutedInStillDisabledHarness,
                    VaultCryptoDependencyCapability.RandomizedAeadBehavioralKatsExecutedInStillDisabledHarness,
                    VaultCryptoDependencyCapability.IntegratedVerificationOrderKatsExecutedInStillDisabledHarness,
                    VaultCryptoDependencyCapability.StillDisabledProviderFacadeBoundaryModeled,
                    VaultCryptoDependencyCapability.VaultContainerContractModeled,
                    VaultCryptoDependencyCapability.InMemoryVaultContainerParserWriterTested,
                    VaultCryptoDependencyCapability.ManifestContractModeled,
                    VaultCryptoDependencyCapability.InMemoryManifestParserWriterTested,
                    VaultCryptoDependencyCapability.LocalManifestStaleRecordDecisionPolicyTested,
                    VaultCryptoDependencyCapability.StoragePolicyContractModeled,
                    VaultCryptoDependencyCapability.PlatformStorageBoundaryContractModeled,
                    VaultCryptoDependencyCapability.AtomicityCrashRecoveryContractModeled,
                    VaultCryptoDependencyCapability.AtomicWriteStrategyContractModeled,
                    VaultCryptoDependencyCapability.CrashRecoveryContractModeled,
                    VaultCryptoDependencyCapability.StorageInterruptionTestContractModeled,
                    VaultCryptoDependencyCapability.InMemoryStorageAtomicityCrashSimulatorTested,
                    VaultCryptoDependencyCapability.StorageFailureModelContractModeled,
                    VaultCryptoDependencyCapability.StorageNamespacePathHygieneContractModeled,
                    VaultCryptoDependencyCapability.StorageNamespacePathPolicyImplementedTested,
                    VaultCryptoDependencyCapability.StorageLayoutPlanImplementedTested,
                    VaultCryptoDependencyCapability.PathContainmentPlannerImplementedTested,
                    VaultCryptoDependencyCapability.PlatformStorageRootContractModeled,
                    VaultCryptoDependencyCapability.PlatformRootSettingsPolicyModeled,
                    VaultCryptoDependencyCapability.AndroidAppPrivateRootPolicyModeled,
                    VaultCryptoDependencyCapability.LinuxRootSettingsPolicyModeled,
                    VaultCryptoDependencyCapability.LinuxCustomRootValidationPolicyImplementedTested,
                    VaultCryptoDependencyCapability.LinuxRootResolutionPolicyImplementedTested,
                    VaultCryptoDependencyCapability.PlatformRootResolverBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.PlatformPathConstructionBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.StorageSafetyPreflightBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.DisabledStorageServiceFacadeImplementedTested,
                    VaultCryptoDependencyCapability.StorageOperationFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.PersistenceReadinessGateImplementedTested,
                    VaultCryptoDependencyCapability.PersistenceReadinessFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.LockSessionLifecycleBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.LockSessionFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.RedactionLeakageBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.RedactionLeakageFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.PassphrasePolicyBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.PassphrasePolicyFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.ClearWipeStrategyBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.ClearWipeFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.MigrationCorruptionBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.MigrationCorruptionFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.ProviderOperationAuthorizationBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.ProviderOperationFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.RuntimeRandomnessAuthorizationBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.RuntimeRandomnessFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.KdfCalibrationAuthorizationBoundaryImplementedTested,
                    VaultCryptoDependencyCapability.KdfCalibrationAuthorizationFailureVocabularyModeled,
                    VaultCryptoDependencyCapability.OsKeyringPassphraseStorageRejected,
                    VaultCryptoDependencyCapability.PasswordManagerIntegrationRejected,
                    VaultCryptoDependencyCapability.PassphraseFirstVaultAuthorityModeled,
                    VaultCryptoDependencyCapability.SafePathConstructionContractModeled,
                    VaultCryptoDependencyCapability.SymlinkTraversalContractModeled,
                    VaultCryptoDependencyCapability.StoragePermissionOwnershipContractModeled,
                    VaultCryptoDependencyCapability.DurabilityCapabilityContractModeled,
                    VaultCryptoDependencyCapability.DurabilityFailClosedPolicyModeled,
                    VaultCryptoDependencyCapability.WarningOnlyDurabilityRejectionModeled,
                    VaultCryptoDependencyCapability.RollbackLimitationAntiRollbackAnchorModeled,
                    VaultCryptoDependencyCapability.SecureStorageBoundaryContractModeled,
                    VaultCryptoDependencyCapability.Argon2idCalibrationPolicyModeled,
                    VaultCryptoDependencyCapability.Argon2idCandidateParameterPolicyModeled,
                    VaultCryptoDependencyCapability.Argon2idCalibrationPolicyImplementedTested,
                    VaultCryptoDependencyCapability.Argon2idCandidateSelectionPolicyImplementedTested,
                    VaultCryptoDependencyCapability.Argon2idMemoryFailureHandlingModeledTested,
                    VaultCryptoDependencyCapability.Argon2idStoredParameterNoDowngradeModeledTested,
                    VaultCryptoDependencyCapability.AndroidArgon2idCalibrationEvidenceCaptureModeled,
                    VaultCryptoDependencyCapability.AndroidCompatibilityEntropyPolicyModeled,
                    VaultCryptoDependencyCapability.RuntimeRandomnessProviderChecksModeled,
                    VaultCryptoDependencyCapability.ProductionProviderAcceptanceContractModeled,
                    VaultCryptoDependencyCapability.VaultHeaderCommitmentPolicyModeled,
                    VaultCryptoDependencyCapability.HkdfSha256KeyExpansionPolicyModeled,
                    VaultCryptoDependencyCapability.HmacSha256HeaderCommitmentPrimitiveModeled,
                    VaultCryptoDependencyCapability.KeyExpansionOutputLayoutModeled,
                    VaultCryptoDependencyCapability.PrimitiveThreatModelRationaleModeled,
                    VaultCryptoDependencyCapability.CanonicalHeaderByteVectorContractModeled,
                    VaultCryptoDependencyCapability.HkdfSha256VectorContractModeled,
                    VaultCryptoDependencyCapability.HmacSha256HeaderCommitmentVectorContractModeled,
                    VaultCryptoDependencyCapability.CanonicalHeaderEncodingPolicyModeled,
                    VaultCryptoDependencyCapability.KeySeparationLabelsPolicyModeled,
                    VaultCryptoDependencyCapability.CanonicalHeaderSerializerVectorTested,
                    VaultCryptoDependencyCapability.HkdfSha256KeyExpansionVectorTested,
                    VaultCryptoDependencyCapability.HmacSha256HeaderCommitmentVectorTested,
                    VaultCryptoDependencyCapability.StrictAadContractPolicyModeled,
                    VaultCryptoDependencyCapability.StrictAadSerializationVectorTested,
                    VaultCryptoDependencyCapability.TinkRecordAeadBuildingBlockTested,
                    VaultCryptoDependencyCapability.TinkNonKeyCommitmentMitigationModeled,
                    VaultCryptoDependencyCapability.PassphraseEncodingPolicyModeled,
                    VaultCryptoDependencyCapability.PassphrasePolicyValidationImplemented,
                    VaultCryptoDependencyCapability.Argon2idPassphraseRootDerivationVectorTested,
                    VaultCryptoDependencyCapability.TinkRawKeyFeasibilityPolicyModeled,
                    VaultCryptoDependencyCapability.Argon2idBoundedCalibrationPolicyModeled,
                    VaultCryptoDependencyCapability.Argon2idCalibrationProbeOnly,
                    VaultCryptoDependencyCapability.AndroidArtifactPinned,
                    VaultCryptoDependencyCapability.DesktopArtifactPinned,
                    VaultCryptoDependencyCapability.PureJvmNoNativeLibraries,
                    VaultCryptoDependencyCapability.SplitProviderStack,
                ),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.KdfFinalParameterApprovalMissing,
                    VaultCryptoDependencyBlocker.RequiresSplitProviderDesign,
                    VaultCryptoDependencyBlocker.ProductionProviderImplementationMissing,
                    VaultCryptoDependencyBlocker.ProviderSelectionProductionBlocked,
                    VaultCryptoDependencyBlocker.ProductionProviderAcceptanceContractIncomplete,
                    VaultCryptoDependencyBlocker.StillDisabledProviderIntegrationHarnessNotSelectable,
                    VaultCryptoDependencyBlocker.StillDisabledProviderFacadeNotSelectable,
                    VaultCryptoDependencyBlocker.StaleRecordManifestIntegrationMissing,
                    VaultCryptoDependencyBlocker.VaultContainerPersistenceImplementationMissing,
                    VaultCryptoDependencyBlocker.ManifestReadWriteImplementationMissing,
                    VaultCryptoDependencyBlocker.StorageSuccessPathAbsent,
                    VaultCryptoDependencyBlocker.DisabledStorageServiceFacadeStillDisabled,
                    VaultCryptoDependencyBlocker.PersistenceReadinessGateStillBlocked,
                    VaultCryptoDependencyBlocker.PlatformStorageImplementationMissing,
                    VaultCryptoDependencyBlocker.AtomicWriteImplementationMissing,
                    VaultCryptoDependencyBlocker.CrashRecoveryImplementationMissing,
                    VaultCryptoDependencyBlocker.StorageInterruptionTestsMissing,
                    VaultCryptoDependencyBlocker.StorageFailureRuntimeMappingMissing,
                    VaultCryptoDependencyBlocker.StoragePathConstructionImplementationMissing,
                    VaultCryptoDependencyBlocker.PlatformStorageRootImplementationMissing,
                    VaultCryptoDependencyBlocker.PlatformRootSettingsImplementationMissing,
                    VaultCryptoDependencyBlocker.SettingsUiImplementationMissing,
                    VaultCryptoDependencyBlocker.SettingsPersistenceImplementationMissing,
                    VaultCryptoDependencyBlocker.SafePathConstructionImplementationMissing,
                    VaultCryptoDependencyBlocker.SymlinkTraversalImplementationMissing,
                    VaultCryptoDependencyBlocker.StoragePermissionOwnershipImplementationMissing,
                    VaultCryptoDependencyBlocker.DurabilityCapabilityProbeImplementationMissing,
                    VaultCryptoDependencyBlocker.DurabilityFailClosedRuntimeEvidenceMissing,
                    VaultCryptoDependencyBlocker.WarningOnlyDurabilityPersistenceRejected,
                    VaultCryptoDependencyBlocker.AntiRollbackAnchorAbsentNoFullRollbackClaim,
                    VaultCryptoDependencyBlocker.ManifestStorageAtomicityReviewMissing,
                    VaultCryptoDependencyBlocker.Argon2idBoundedCalibrationApprovalMissing,
                    VaultCryptoDependencyBlocker.LockSessionLifecycleStillDisabled,
                    VaultCryptoDependencyBlocker.RedactionLeakageBoundaryStillDisabled,
                    VaultCryptoDependencyBlocker.RedactionLeakageRuntimeReviewMissing,
                    VaultCryptoDependencyBlocker.PassphrasePolicyBoundaryStillDisabled,
                    VaultCryptoDependencyBlocker.PassphrasePolicyRuntimeReviewMissing,
                    VaultCryptoDependencyBlocker.ClearWipeStrategyBoundaryStillDisabled,
                    VaultCryptoDependencyBlocker.ClearWipeStrategyRuntimeReviewMissing,
                    VaultCryptoDependencyBlocker.MigrationCorruptionBoundaryStillDisabled,
                    VaultCryptoDependencyBlocker.MigrationCorruptionRuntimeReviewMissing,
                    VaultCryptoDependencyBlocker.MigrationCorruptionTestsMissing,
                    VaultCryptoDependencyBlocker.ProviderOperationAuthorizationBoundaryStillDisabled,
                    VaultCryptoDependencyBlocker.ProviderOperationAuthorizationRuntimeReviewMissing,
                    VaultCryptoDependencyBlocker.ProviderOperationAuthorizationTestsMissing,
                    VaultCryptoDependencyBlocker.RuntimeRandomnessAuthorizationBoundaryStillDisabled,
                    VaultCryptoDependencyBlocker.RuntimeRandomnessAuthorizationRuntimeReviewMissing,
                    VaultCryptoDependencyBlocker.RuntimeRandomnessAuthorizationTestsMissing,
                    VaultCryptoDependencyBlocker.KdfCalibrationAuthorizationBoundaryStillDisabled,
                    VaultCryptoDependencyBlocker.KdfCalibrationAuthorizationRuntimeReviewMissing,
                    VaultCryptoDependencyBlocker.KdfCalibrationAuthorizationTestsMissing,
                    VaultCryptoDependencyBlocker.ProductionStorageReviewMissing,
                    VaultCryptoDependencyBlocker.MainnetReleaseHardeningReviewMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Selected only as a reviewed candidate after Android/Linux compile and packaging feasibility, desktop and Android runtime public KAT validation, local dependency/POM license inspection, package inventory review, Tink keyset/storage review, desktop and Android test-scope Tink raw-key public API feasibility probing, Bouncy Castle Argon2id API risk review, split-provider boundary review, disabled provider-boundary modeling, provider-selection boundary modeling, provider-level KAT strategy modeling for deterministic vectors plus randomized AEAD behavioral checks, integrated verification-order KAT modeling, vault container/manifest/stale-record modeling, platform storage boundary modeling, platform storage-root contract modeling, platform root settings policy modeling, Linux custom root static validation fixture testing, Linux root-resolution evidence fixture testing, platform root resolver boundary fixture testing, platform path-construction boundary fixture testing, storage safety preflight boundary fixture testing, disabled storage service facade fixture testing, redaction/leakage boundary fixture testing, passphrase policy boundary fixture testing, clear/wipe strategy boundary fixture testing, migration/corruption boundary fixture testing, provider operation authorization boundary fixture testing, runtime randomness authorization boundary fixture testing, KDF calibration authorization boundary fixture testing, safe path-construction contract modeling, symlink/traversal contract modeling, permission/ownership contract modeling, durability capability contract modeling, durability fail-closed and warning-only rejection policy modeling, atomic write strategy modeling, crash-recovery contract modeling, interruption-test contract modeling, in-memory storage atomicity/crash simulator testing, storage failure model modeling, storage namespace/path hygiene modeling, storage namespace/path policy fixture testing, rootless logical storage layout plan fixture testing, path-containment planner fixture testing, secure-storage boundary contract modeling, in-memory vault container parser/writer fixture testing, in-memory manifest parser/writer fixture testing, local manifest-relative stale-record decision testing, explicit no-full-local-directory-rollback claim without an anti-rollback anchor, test-only provider KAT harness modeling, implemented-still-disabled Argon2id calibration floor/candidate-selection/memory-failure/no-downgrade policy, manual Android calibration evidence-capture modeling, Android compatibility/entropy policy modeling, runtime randomness provider check modeling, v1 production-provider acceptance-contract modeling, header commitment policy modeling, HKDF-SHA-256 key-expansion policy modeling, HMAC-SHA-256 header-commitment primitive modeling, key-expansion output layout modeling, primitive threat-model rationale modeling, canonical header/HKDF/HMAC vector contract modeling, canonical header encoding policy modeling, key-separation labels modeling, still-disabled canonical header serializer/HKDF/HMAC implementations that match the non-secret vectors, strict AAD serialization and Tink record AEAD building blocks that match non-secret tests, Tink non-key-commitment mitigation modeling, passphrase encoding policy modeling and implementation, explicit-parameter Bouncy Castle Argon2id root derivation fixture testing, still-disabled provider integration harness execution of deterministic provider-level vectors plus randomized AEAD behavioral KATs in the required verification order, a still-disabled metadata-only provider facade, and a disabled vault storage service facade whose operations only return disabled evidence. The passphrase policy boundary is model-only evidence for future passphrase input, normalization, encoding, retry, throttle, lockout, redaction, clear/wipe, and unlock-prerequisite policy; it does not accept raw passphrases, hash or fingerprint passphrases, run KDFs, implement retry/throttle/lockout, enable unlock, enable persistence, or enable provider selection. The clear/wipe strategy boundary is model-only evidence for future sensitive value classes, lifecycle triggers, strategy requirements, and JVM zeroization limitations; it does not accept raw sensitive values, clear real memory, prove JVM zeroization, call provider or storage clear operations, invalidate real sessions, enable unlock, enable persistence, or enable provider selection. The migration/corruption boundary is model-only evidence for future container/version/manifest/index/record evidence categories, failure classes, fail-closed actions, stale and rollback suspicion handling, interrupted-write handling, recovery requirements, quarantine requirements, and redacted failure reporting; it does not parse real storage, run migration or dry-runs, repair storage, quarantine records, recover records, verify AEAD tags, verify real header commitments, enable unlock, enable persistence, or enable provider selection. The provider operation authorization boundary is model-only evidence for future provider operation kinds, purposes, required gates, blockers, warnings, and disabled capabilities; it does not authorize provider operations, run provider KATs, run runtime randomness checks, generate entropy/salts/nonces/keys, run KDF/Argon2id/HKDF/HMAC/AEAD, compute or verify real header commitments, encrypt or decrypt records, wrap or unwrap keys, clear providers, enable unlock, enable persistence, or enable provider selection. The runtime randomness authorization boundary is model-only evidence for future runtime entropy, OS CSPRNG, provider randomness, salt, nonce, key-generation input, platform entropy review, blockers, warnings, and disabled capabilities; it does not authorize randomness operations, call OS or provider randomness, run randomness health checks, generate entropy/salts/nonces/keys, authorize deterministic test-vector randomness for production runtime, enable provider operations, enable unlock, enable persistence, or enable provider selection. The KDF calibration authorization boundary is model-only evidence for future Argon2id/KDF calibration finalization, platform/device class review, parameter evidence, required gates, blockers, warnings, and disabled capabilities; it does not authorize KDF calibration, run Argon2id, run KDFs, run calibration, run benchmarks, approve final parameters, accept passphrases, normalize or encode passphrases, generate or consume salts, enable unlock, enable persistence, or enable provider selection. It remains candidate-only: no final calibrated production parameters, KDF calibration authorization, selectable production provider implementation, provider selection, provider operation authorization, runtime randomness authorization, OS CSPRNG or provider randomness authorization, entropy/salt/nonce/key generation, platform storage implementation, storage safety preflight filesystem checks, disabled storage service success path, runtime redaction/logging/crash-reporting implementation, secret hashing or fingerprinting, passphrase hashing or fingerprinting, passphrase input success path, passphrase normalization/encoding execution path, retry/throttle/lockout implementation, actual clear/wipe or zeroization path, session invalidation path, migration execution, repair execution, quarantine execution, record recovery execution, manifest storage read/write, storage success path, actual path construction, path joining, real path containment check, directory creation, platform root selection or resolution, Linux custom-root resolution, Settings UI, settings persistence, OS keyring passphrase storage, password-manager integration, symlink check, permission check, durability probe, warning-only encrypted vault persistence path, atomic write/recovery implementation, interruption-test runtime hooks, storage failure runtime mapping, anti-rollback anchor, keyset storage, filesystem/database/platform settings vault storage, persistence, or mainnet path is enabled.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.LazysodiumJavaAndroid,
                status = VaultCryptoDependencyProbeStatus.RejectedForCurrentVault,
                pinnedArtifacts = listOf(
                    "com.goterl:lazysodium-java:5.2.0",
                    "com.goterl:lazysodium-android:5.2.0",
                ),
                capabilities = setOf(
                    VaultCryptoDependencyCapability.Argon2idApiPresent,
                    VaultCryptoDependencyCapability.ScryptApiPresent,
                    VaultCryptoDependencyCapability.XChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.AeadApiPresent,
                    VaultCryptoDependencyCapability.HkdfOrPrfApiPresent,
                    VaultCryptoDependencyCapability.AndroidArtifactPinned,
                    VaultCryptoDependencyCapability.DesktopArtifactPinned,
                    VaultCryptoDependencyCapability.AndroidNativeAbiLibrariesPresent,
                    VaultCryptoDependencyCapability.LinuxNativeLibrariesPresent,
                    VaultCryptoDependencyCapability.NativeLibrariesRequired,
                    VaultCryptoDependencyCapability.SinglePrimitiveFamily,
                    VaultCryptoDependencyCapability.SecretStreamApiPresent,
                    VaultCryptoDependencyCapability.FixedNonceKnownAnswerVectorFeasible,
                ),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DependencyReviewIncomplete,
                    VaultCryptoDependencyBlocker.LicenseReviewIncomplete,
                    VaultCryptoDependencyBlocker.KdfCalibrationMissing,
                    VaultCryptoDependencyBlocker.KdfFinalParameterApprovalMissing,
                    VaultCryptoDependencyBlocker.AndroidDuplicateJnaClasspath,
                    VaultCryptoDependencyBlocker.NativePackagingUnverified,
                    VaultCryptoDependencyBlocker.NativePackagingReviewRequired,
                    VaultCryptoDependencyBlocker.NativeLoaderRuntimeRisk,
                    VaultCryptoDependencyBlocker.KnownAnswerVectorTestsMissing,
                    VaultCryptoDependencyBlocker.AndroidKnownAnswerVectorRuntimeMissing,
                    VaultCryptoDependencyBlocker.AndroidRuntimeProbeMissing,
                    VaultCryptoDependencyBlocker.ProductionProviderBoundaryMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Rejected for the current vault branch because the Android package probe failed with duplicate JNA classes before APK output. It is not wired into vault storage or approved for production implementation.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.IonSpinKmpLibsodium,
                status = VaultCryptoDependencyProbeStatus.DeferredAfterComparison,
                pinnedArtifacts = listOf(
                    "com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.9.5",
                    "com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings-jvm:0.9.5",
                    "com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings-android:0.9.5",
                ),
                capabilities = setOf(
                    VaultCryptoDependencyCapability.Argon2idApiPresent,
                    VaultCryptoDependencyCapability.ScryptApiPresent,
                    VaultCryptoDependencyCapability.XChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.NativeLibrariesRequired,
                    VaultCryptoDependencyCapability.SinglePrimitiveFamily,
                ),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DependencyReviewIncomplete,
                    VaultCryptoDependencyBlocker.LicenseReviewIncomplete,
                    VaultCryptoDependencyBlocker.NativePackagingUnverified,
                    VaultCryptoDependencyBlocker.KotlinMultiplatformCompatibilityUnverified,
                    VaultCryptoDependencyBlocker.KnownAnswerVectorTestsMissing,
                    VaultCryptoDependencyBlocker.AndroidKnownAnswerVectorRuntimeMissing,
                    VaultCryptoDependencyBlocker.AndroidRuntimeProbeMissing,
                    VaultCryptoDependencyBlocker.ProductionProviderBoundaryMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Inspected as an exact KMP libsodium candidate but deferred from the build because the current spike did not validate its Kotlin metadata, native-loader behavior, or package outputs.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.BouncyCastleOnly,
                status = VaultCryptoDependencyProbeStatus.InsufficientAsPrimaryVaultStack,
                pinnedArtifacts = listOf("org.bouncycastle:bcprov-jdk18on:1.84"),
                capabilities = setOf(
                    VaultCryptoDependencyCapability.Argon2idApiPresent,
                    VaultCryptoDependencyCapability.ChaCha20Poly1305ApiPresent,
                    VaultCryptoDependencyCapability.AeadApiPresent,
                    VaultCryptoDependencyCapability.PureJvmNoNativeLibraries,
                ),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DoesNotProvidePreferredAead,
                    VaultCryptoDependencyBlocker.KdfCalibrationMissing,
                    VaultCryptoDependencyBlocker.KdfFinalParameterApprovalMissing,
                    VaultCryptoDependencyBlocker.KnownAnswerVectorTestsMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Useful Argon2id provider candidate, but not enough alone for the preferred XChaCha record envelope.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.PlatformCryptoOnly,
                status = VaultCryptoDependencyProbeStatus.RejectedAsDefaultVaultStack,
                pinnedArtifacts = emptyList(),
                capabilities = setOf(VaultCryptoDependencyCapability.AeadApiPresent),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DoesNotProvideArgon2id,
                    VaultCryptoDependencyBlocker.DoesNotProvidePreferredAead,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Rejected as the default vault stack because it pushes toward PBKDF2/AES-GCM-only storage.",
            ),
            VaultCryptoDependencyProbeResult(
                candidate = VaultCryptoDependencyCandidate.KotlinMultiplatformCrypto,
                status = VaultCryptoDependencyProbeStatus.DeferredPendingReview,
                pinnedArtifacts = emptyList(),
                capabilities = emptySet(),
                blockers = setOf(
                    VaultCryptoDependencyBlocker.DependencyReviewIncomplete,
                    VaultCryptoDependencyBlocker.NativePackagingUnverified,
                    VaultCryptoDependencyBlocker.KnownAnswerVectorTestsMissing,
                    VaultCryptoDependencyBlocker.VaultImplementationStillDisabled,
                ),
                implementationEnabled = false,
                storageEnabled = false,
                productionPersistenceEnabled = false,
                mainnetEnabled = false,
                note = "Deferred unless a clearly maintained KMP stack proves Android/Linux packaging and the preferred primitive set.",
            ),
        )
}
